server.port=8081
botengine.admin.username=admin
botengine.admin.password=CAMBIAR_ESTA_CLAVE

spring.datasource.url=jdbc:postgresql://127.0.0.1:${BOTENGINE_DB_PORT}/${BOTENGINE_DB_NAME}
spring.datasource.username=${BOTENGINE_DB_USER}
spring.datasource.password=${BOTENGINE_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true